"use client";
// import type { Metadata } from "next";
import "./globals.css";
import TopNav from "./components/TopNav";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentPath = usePathname();
  // console.log("current page: " + currentPath);
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <TopNav currentPath={currentPath} />
        {children}
      </body>
    </html>
  );
}
